[build]
  publish = "build"
  command = "npm run build"

  [[headers]]
  for = "/swagger.yaml"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"