[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS, PUT, DELETE, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/v1/*"
  to = "https://proxy.scalar.com/?scalar_url=https://wallet.release.newpay.com.ar/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/scalar/*"
  to = "https://proxy.scalar.com/?scalar_url=https://wallet.release.newpay.com.ar/scalar/:splat"
  status = 200
  force = true